{
	"version": 1740637323,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/play-sheet0.png",
		"images/trumpgoldcardbg-sheet0.png",
		"images/trump-sheet0.png",
		"images/biden-sheet0.png",
		"images/biden-sheet1.png",
		"images/biden-sheet2.png",
		"images/particles.png",
		"images/particles2.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/clash.m4a",
		"media/clash.ogg",
		"media/plus score sound.m4a",
		"media/plus score sound.ogg",
		"media/results.m4a",
		"media/results.ogg",
		"media/trump 1.m4a",
		"media/trump 1.ogg",
		"media/trump 2.m4a",
		"media/trump 2.ogg",
		"media/trump 3.m4a",
		"media/trump 3.ogg",
		"media/button_click.m4a",
		"media/button_click.ogg",
		"media/trump gold card bgm.m4a",
		"media/trump gold card bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}